### ISSUE TITLE
DB에 저장할 때 챔피언 이름이 한글로 저장되는 현상

### ISSUE THREAD

**Issue by sh05158** [CAU-OSS-2019/team-project-team17#3]
DB에 저장할 때 챔피언 이름을 영문으로 저장해야 되는데,
크롤링 오류로 한글로 DB에 저장하고 있습니다.
크롤링 팀 수정 부탁드립니다!

**Comment by weenybeenymini** [comment]
base_character_name은 주소 링크에서 긁어와 영어로 db에 저장되는 반면,
best_character_name은 페이지에서 긁어오기 때문에 한국어로 저장되는 일이 일어났습니다.
현재 한국 페이지가 아닌 그냥 페이지로 페이지를 가져오는 링크를 변환하여
둘 다 영어로 저장되게 끔 변경하였고 crawling branch에 edit_eng_name으로 커밋하였습니다
디비에도 데이터를 바꿔서 추가하여 놓겠습니다!
